[package]
name = "checkpoint-table"
version = "0.1.0"
edition = "2021"
publish = false

[features]
default = ["arrow"]
arrow = ["arrow-60"]
arrow-60 = ["common/arrow-60"]
arrow-59 = ["common/arrow-59"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
common = { path = "../common", default-features = false }
delta_kernel = { path = "../../../kernel", features = [
  "default-engine-base",
  "internal-api",
] }
delta_kernel_default_engine = { path = "../../../default-engine", features = ["rustls"] }
env_logger = "0.11.8"
tokio = { version = "1.0", features = ["full"] }
url = "2"
bytes = "1.11.0"
futures = "0.3.31"

# for cargo-release
[package.metadata.release]
release = false
