[package]
name = "read-table-single-threaded"
version = "0.1.0"
edition = "2021"
publish = false

[features]
default = ["arrow"]
arrow = ["arrow-60"]
arrow-60 = ["common/arrow-60"]
arrow-59 = ["common/arrow-59"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
common = { path = "../common", default-features = false }
delta_kernel = { path = "../../../kernel", features = [
  "default-engine-base",
  "internal-api",
  "prettyprint",
] }
delta_kernel_default_engine = { path = "../../../default-engine", features = ["rustls"] }
env_logger = "0.11.8"
itertools = "0.14"

# for cargo-release
[package.metadata.release]
release = false
