[workspace]
members = [
    "acceptance",
    "benchmarks",
    "default-engine",
    "default-engine/test-utils",
    "derive-macros",
    "ffi",
    "kernel",
    "kernel/examples/*",
    "test-utils",
    "workloads",
    "feature-tests",
    "mem-test",
    "unity-catalog-delta-rest-client", # WIP: this is an experimental UC client for catalog-managed table work
    "delta-kernel-unity-catalog", # WIP: this is an experimental UC catalog implementation
    "unity-catalog-delta-client-api", # WIP: transport-agnostic UC client API traits
]
# note that in addition to the members above, the workspace includes examples:
# - inspect-table
# - read-table-changes
# - read-table-multi-threaded
# - read-table-single-threaded
# - write-table
resolver = "3"

[workspace.package]
edition = "2021"
homepage = "https://delta.io"
keywords = ["deltalake", "delta", "datalake"]
license = "Apache-2.0"
repository = "https://github.com/delta-io/delta-kernel-rs"
readme = "README.md"
rust-version = "1.88"
version = "0.29.0"
