[package]
name = "inspect-table"
version = "0.1.0"
edition = "2021"
publish = false

[features]
default = ["arrow"]
arrow = ["arrow-60"]
arrow-60 = ["common/arrow-60"]
arrow-59 = ["common/arrow-59"]

[dependencies]
chrono = "0.4.42"
clap = { version = "4.5", features = ["derive"] }
common = { path = "../common", default-features = false }
delta_kernel = { path = "../../../kernel", features = [
  "default-engine-base",
  "internal-api",
] }
delta_kernel_default_engine = { path = "../../../default-engine", features = ["rustls"] }
env_logger = "0.11.8"
tracing = "0.1"
tracing-subscriber = { version="0.3.22", features = [ "env-filter" ] }

# for cargo-release
[package.metadata.release]
release = false
