[package]
name = "mem-test"
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
rust-version.workspace = true
version.workspace = true

# for cargo-release
[package.metadata.release]
release = false

[features]
default = ["arrow"]
arrow = ["arrow-60"]
arrow-60 = ["delta_kernel/arrow-60"]
arrow-59 = ["delta_kernel/arrow-59"]

[dependencies]
delta_kernel = { path = "../kernel", features = ["default-engine-base"] }
delta_kernel_default_engine = { path = "../default-engine", features = ["rustls"] }
dhat = "0.3"
rayon = "1.10"
serde_json = "1"
tempfile = "3"
tracing = "0.1"
url = "2"
