[package]
name = "common"
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
version.workspace = true

# for cargo-release
[package.metadata.release]
release = false

[features]
default = ["arrow"]
arrow = ["arrow-60"]
arrow-60 = ["delta_kernel/arrow-60"]
arrow-59 = ["delta_kernel/arrow-59"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
delta_kernel = { path = "../../../kernel", features = [
  "default-engine-base",
  "internal-api",
] }
delta_kernel_default_engine = { path = "../../../default-engine", features = ["rustls"] }
url = "2"
